[[section-introduction-and-goals]]
== Introduction and Goals
This document is a description of the work done during the course of software architecture in the University of Oviedo. The aim of the course is to create an application called Randarin. The purpose of it is to facilitate meeting between friends using new technologies managing the information of the users in a decentralized way using the SOLID project. The information of the user will only be able to be used if the user give us permission to do so.

The members of our team are:

* Irene Bello
* Sergio Riestra
* Sergio Fernández
* Raúl Núñez García
* Armando Campa Martínez
* Francisco Manuel Fernández Suárez


[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

The two main requirements are:

* building a Web application that will run in a server and will store locations in a decentralized way.
* building an application that will run in a mobile phone speaking to the server and receiving notifications when friends in the app are near.

The other requirements the application will have are:

* The application will store the minimal information about a user; the rest will be on a user pod.
* The system will be deployed from docker containers and in a cloud service
* The web application will contain some monitoring system.
* It is required to develop unit tests, acceptances test and load test.


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
|===
|Priority|Goal|Description
| 1 | Security | It will not store personal information about the user, it will ask permission to access this information.
| 2 | Usability | The final application should be easy to use for the first time for new users.
| 3 | Efficiency | The final application should work with small waiting times and doing its functionality without any error.
| 4 | Testability | We should be able to create and run test to check that the application works as needed.
|===


=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Teacher | labra@uniovi.es | Oversee the project and check that the requirements are met
| Developer team | The ones developing the app | Make an usable application and learn about software architecture.
| Users | People that use the final application | They want a funcitonal application that is easy to use, that does not use information unless they want to.
|===
