[[section-solution-strategy]]
== Solution Strategy
In order to this project with the requirements explained earlier, we have to make some decisions regarding the aplication and how to aproach the problem we encounter in the development of this project.

=== Technology Decisions
In order to develop the aplication with the constraints required we had to chose some technologies that will help us do so.
* Web aplication that is adaptable: At first we decided to do both a web application and a mobile application. However, we found that the later gave us a lot of problems (using react native). We did not have the time to solve them for the final project so we decided to do a web application with all the functionality instead.
* Monitoring: For this we are using Prometheous and Grafana, this was decided because it was well explaind in the laboratories.
* Testing: To test the correct purpose of the aplication we are using the E2E test, the Gatling test and the react testing library.
* Web application development: For the development of the application we choose to use react, express and node.js. The squeleton of the app was provided to us with this technologies so we continued to use them.
* Application deployment: We are using Docker and Heroku, as this is a requirement for this app.
* Bootstrap: This library was use for some components of the application, as the popover.
* Database: We choose to use the mongoDB database, this was the one choosen in the squeleton of the app so we choose to continue using this.
* Login with pods: To log in with pods we decided to use @inrupt/solid-ui-react library.
* Map: To implement the map we use a library called leaflet. At first we decided to use Google Maps but with leaflet this was easier to do.
* Notifications: To use the notifications we uses the library react-tostify.
* Other libraries: Some other libraries where used, but for the main requirements this ones are the most important. For example, solid libraries that will be employed for user data management.

=== Development tools
==== IDEs

Mainly, we use Visual Studio Code, for its versatility to work on many different languajes and document formats. It also provides git integration, which is very useful for version control.

==== Documentation and visual tools
 
For diagrams and other visuals, our initial choice is draw.io, a quite useful tool for drawing graphs and similar media.

=== Organizational Decisions

Due to the weekly nature of the laboratory classes, the team can work in a semi-agile way. That is, we are not using from the start a specific variant such as Kanban, but the timing allows us to split work among us and set a constant time frame to work, as a sprint.

The sprints consist on the week in-between laboratory classes. In each class a meeting is held (online, due to Covid-19 regulations), and it works as an end-of-sprint meeting as well as a meeting to decide the next assignments. Additional meetings may be held as way of tracking progress and group-decission taking. The meetings logs are registered in the GitHub repository wiki.
The team is also connected via other channels such as Microsoft Teams for small updates and decisions.

Initially, personal git branches were made, with everyone making pull requests to the master branch. Later, it was decided that it was best to make a branch for each implementation (one for the webapp, one for the restapi, and so on), seeing as we swapped branches to work together on multiple things. They were periodically committed to the master branch.
