[[section-concepts]]
== Cross-cutting Concepts

=== Design patterns

In order to access and manipulate data in a clean way, the MVC pattern was the chosen one to start developing. 

This way, as it will be developed in React, it is one of the best options for accessing to the solid pods.

Regarding the backend part, there will be a model to define the database skelleton and routes to get every action. This way, a controller will orchestrate the main crud functionality apart from the ones that would be potentially required.

Once it is required, there can also be applied more design patters as needed.

=== Security
As the architecture of the application is decided, this section will be updated.

It will be a crutial part to deal with, ensuring the user secure accesses via secure https protocol, having all the time validation constraints to avoid undesirable risks.

=== Technical decisions
* In the data model of the restapi, we unified the user model with the location model, since the user is always going to have the latest location available.
* When dealing with the api in the restapi, we coult just ommit the controller part working directly in the api part thanks to the solid-node-client. This way, we would be able to let the webapp and the mobile app working directly with the pods that this layer provides. 

=== Intenationalization
From the popular point of view of every application (and specifically for this one which deals with locations and people), it looks like as if it was mandatory to produce a well based multilanguage application, and the best option is always at the beginning of the design. 

Otherwise, during it's lifetime it would be much more expensive to trace if the app gets popular in more regions.

