[[section-design-decisions]]
== Design Decisions
=== Webapp
==== Framework and libraries
Choosing framework and libraries we are going to work with. We decided to use the React framework because we can use it for building great user interfaces for the web, has a lot of libraries that can be used to facilitate the implementation on the web and has a lot of other advantages that we thought were very importat to have.

==== Internacionalization
Deciding wether or not start the implementation of the internacionalization from the beggining. Event thought it is not a requirement for this project, we decided to do the internacionalization of this application from the begginig. This is because in other courses we attended doing the internacionalization at the end of the implentation of the appliaction was very time consuming and doing it while implementing is not so much. This is a task that is easily done, so we started to implement this from day one.

==== Pods provider
Choosing the provider of the pods that we are going to use. At the first working application deployed was being implemented we encoutered some problems with some of the providers of the solid providers. For example while using a map we needed a fixed provider and also to do the automatic login also. So we decided to use the solid comunity provider.

==== Login in the app
Making the log in authomated using solid. While doing the log in in the app we found that doing this with the solid components was the better option. This is used because because it is more secure that doing it without this components.

==== Admin options
Admin options. While implementing the admin user and the thing this role was able to do we found that forbidding this users to log in/ register again in the app was not a good practice. So we decided to remove de imformation about the user in the database but that the user was free to log in again if they want.

==== Locations
Choosing whether or not the user is going to be able to see the locations stored it the pod in the map. We decided that we are going to display all the locations a user has in its pod because we are also going to list them and it is going to be easier for the user to see the location in the map and not only whith the coordinates.

==== Map provider
Choosing wich kind of map provider we are going to use. We decided to use leaflet because it has a library with component of react that is very complete. Also because the api lets us do several daily request. 

==== Notifications
We need to do the notifications for the user that are near us. But, what we define as near? We decided that because of covid and working from home it was best to notify the user of the nearest one. Even if it is kilometers away.

==== Automated location
We saved the lations each time the user wanted but we had a problem, when a user is new we did not show any location. Show to improve this we make that the location is automatically stored in an interval of time, so the user can see a location even if we did not store any yet.

==== Location tag
In our first draft of the aplication we didn't have tags in our location so it was difficult to know which one we are seen or deleting. For this purpose we decided to include tags in the locations we save manually in our pod.
This tags can be seen in the table of all the locations. Furthermore, we can filter de locations with the tag so we can search in a easy way the location we need.

==== Deleting locations from the map
One of the requirements was to manage the locations. At first we deleted the locations via a list of all of them. The problem was that we where not sure what location we where deleting because the informations we had was the coordinates and the tag.
The solution we had is to implement a option to delete the locations in the map. Doing this the user can certainly know wich location is deleting for their pod.

=== Restapi

==== Controllers in the api
Using controllers in the api. We decided that the use of the controllers and the routes was not a good implementation because the methods in the api where a few and in this way we have all the code in one place so it is easier to understand and change.

==== Pods access
Pods access. Even if there is a posibility to work with the pods directly from the restapi we decided we where going to do them in the webapp. Whis is uncomplicated to do this in the webapp.

==== Security
Implementing a thorough security for our restapi. We don´t have a lot of time to implement this sice we are in a time constraingt, so we decided to implement the basic security for this part. We are using CORS to do this. This works because we only allow to make rest api calls from a number of url we know that are safe, our application ones.

=== MobileApp
==== Framework
Choosing the framework to work. We decided to use react-native with expo to do this. We can see the changes in the emulator and also in physical device. Also expo has a lot of libraries that are going to be used to implement this app.

==== PODS usage
Usage of the pods. We had several issues to do this, there seems to be some errors and difficulties to implement this. So we decided this part of the application is being suspended at the moment. Some errors we encountered where the use of the solid components with react-native. The libreries we used work with Node.js without any problem. But since we do not work with a node.js framework perse some libraries do not work properly.

