[[section-design-decisions]]
== Design Decisions

As the design phases starts and progresses this section will be filled.

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

Problems
In this part we will list the problems we encounter in the project during the implementation process. Since we did not start this at this point, this is going to be filled during the next weeks.

Decisions
In this part of the documentation we will write the decisions we made to solve the problems that are above. Since we do not have any problem yet we have this part empty.
